export const AUTHORS = [
  {
    id: "a1",
    name_ar: "د. سارة الخطيب",
    name_en: "Dr. Sara Al-Khatib",
    bio_ar: "باحثة وكاتبة مهتمة بالثقافة والمجتمع.",
    bio_en: "Researcher and writer interested in culture and society.",
    avatar: "https://i.pravatar.cc/120?img=12",
  },
  {
    id: "a2",
    name_ar: "محمد العلي",
    name_en: "Mohammed Al-Ali",
    bio_ar: "صحفي ومترجم، يكتب عن الأدب والفنون.",
    bio_en: "Journalist and translator, writes about literature and arts.",
    avatar: "https://i.pravatar.cc/120?img=5",
  },
];

export const ARTICLES = [
  {
    id: "art1",
    title_ar: "المدينة والذاكرة",
    title_en: "The City and Memory",
    excerpt_ar: "كيف تختزن المدن حكاياتنا؟",
    excerpt_en: "How do cities store our stories?",
    content_ar: "المدينة كتاب مفتوح على وجوه لا تعدّ، كل زاوية فيها تهمس باسم من رحل أو بقي.",
    content_en: "The city is an open book with countless faces; every corner whispers a name of someone who left or stayed.",
    authorId: "a1",
    category: "أدب",
    date: "2025-09-21",
  },
  {
    id: "art2",
    title_ar: "بين الضجيج والصمت",
    title_en: "Between Noise and Silence",
    excerpt_ar: "تأملات في المشهد الثقافي المعاصر.",
    excerpt_en: "Reflections on the contemporary cultural scene.",
    content_ar: "يرتدي المشهد قناعا من أصوات متقاطعة، لكن الصمت غالبا ما يقول ما لا تستطيع الكلمات قوله.",
    content_en: "The scene wears a mask of intersecting voices, but silence often says what words cannot.",
    authorId: "a2",
    category: "ثقافة",
    date: "2025-09-18",
  },
  {
    id: "art3",
    title_ar: "مفردات الرحيل",
    title_en: "Vocabulary of Departure",
    excerpt_ar: "مقالات سريعة عن الاغتراب والعودة.",
    excerpt_en: "Short essays on exile and return.",
    content_ar: "الرحيل كلمة يختلف معناها حسب زمن النطق وبطء العقل في تذكر الطرائق.",
    content_en: "Departure is a word whose meaning shifts depending on the time it is spoken and the mind's slowness to recall paths.",
    authorId: "a1",
    category: "رأي",
    date: "2025-09-10",
  },
  {
    id: "art4",
    title_ar: "قهوة ومسافة",
    title_en: "Coffee and Distance",
    excerpt_ar: "حوارات قصيرة في المقاهي.",
    excerpt_en: "Short conversations in cafés.",
    content_ar: "المقهى مكان للاكتشاف، حيث يمكن للغريب أن يصبح مرآةً مؤقتة.",
    content_en: "The café is a place of discovery, where a stranger can become a temporary mirror.",
    authorId: "a2",
    category: "مقالات",
    date: "2025-08-30",
  },
];
